//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。C_Activity
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Activity
    {
		//add commit
        public System.Guid aId { get; set; }
        public string aTitle { get; set; }
        public string aPlace { get; set; }
        public string aContent { get; set; }
        public Nullable<System.DateTime> aDatetime { get; set; }
        public Nullable<System.Guid> personId { get; set; }
    }
}
