//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AlbumInfo
    {
        public System.Guid aiId { get; set; }
        public string aiUrl { get; set; }
        public string aiDesc { get; set; }
        public Nullable<System.Guid> albumId { get; set; }
        public Nullable<System.DateTime> aiAddTime { get; set; }
        public string aiAction { get; set; }
    }
}
