//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Album
    {
        public System.Guid aId { get; set; }
        public string aName { get; set; }
        public string aPhoto { get; set; }
        public string aIntro { get; set; }
        public string personId { get; set; }
        public Nullable<System.DateTime> aAddTime { get; set; }
        public Nullable<int> aClicks { get; set; }
        public string aTags { get; set; }
        public System.Guid classId { get; set; }
    }
}
