//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class C_Answer
    {
        public System.Guid aId { get; set; }
        public Nullable<System.DateTime> aAddTime { get; set; }
        public string aContent { get; set; }
        public string aNickName { get; set; }
        public string aEmail { get; set; }
        public Nullable<System.Guid> qId { get; set; }
        public Nullable<int> aGood { get; set; }
        public Nullable<int> aBad { get; set; }
    }
}
