//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class C_CarBrand
    {
        public int cbId { get; set; }
        public string cbName { get; set; }
        public string cbFirstChar { get; set; }
        public string cbEnName { get; set; }
        public int cbParentId { get; set; }
        public int cbOrderIndex { get; set; }
    }
}
