//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class C_Car
    {
        public int cId { get; set; }
        public int cbId { get; set; }
        public string cFactoryName { get; set; }
        public string cName { get; set; }
        public string cEnName { get; set; }
        public string cYear { get; set; }
        public string cType { get; set; }
        public string cCountry { get; set; }
        public string cEchnology { get; set; }
        public string cLevel { get; set; }
        public string cEngineCapacity { get; set; }
        public string cTransmission { get; set; }
    }
}
