//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class C_Comment
    {
        public Guid cId { get; set; }
        public Nullable<Guid> cParentid { get; set; }
        public string cAuthor { get; set; }
        public string cEmail { get; set; }
        public string cUrl { get; set; }
        public string cContent { get; set; }
        public Nullable<int> cType { get; set; }
        public Nullable<DateTime> cAddTime { get; set; }
        public Nullable<int> cStatus { get; set; }
    }
}
