//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Movie
    {
        public System.Guid mId { get; set; }
        public string mName { get; set; }
        public string mPhoto { get; set; }
        public string mTips { get; set; }
        public string mCnName { get; set; }
        public string mEnName { get; set; }
        public string mOtherName { get; set; }
        public string mType { get; set; }
        public string mLeadingRole { get; set; }
        public Nullable<System.DateTime> mProduceTime { get; set; }
        public string mProduceCompany { get; set; }
        public string mSellCompany { get; set; }
        public string mMadeCity { get; set; }
        public string mMadeMoney { get; set; }
        public string mMadePlace { get; set; }
        public Nullable<System.DateTime> mMadeTime { get; set; }
        public string mDirector { get; set; }
        public string mScreenWriter { get; set; }
        public string mProducer { get; set; }
        public string mTimeDuration { get; set; }
        public Nullable<System.DateTime> mUpTime { get; set; }
        public string mMoney { get; set; }
        public string mLanguage { get; set; }
        public string mColor { get; set; }
        public string mPrize { get; set; }
        public string mPlayWebSite { get; set; }
        public string mContent { get; set; }
    }
}
