//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Music
    {
        public System.Guid mID { get; set; }
        public string mCnName { get; set; }
        public string mEnName { get; set; }
        public string mTips { get; set; }
        public string mLyricist { get; set; }
        public string mComposer { get; set; }
        public string mStyle { get; set; }
        public string mTimeDuration { get; set; }
        public Nullable<System.Guid> SpecialId { get; set; }
        public string mLyric { get; set; }
    }
}
