//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_News
    {
        public int nId { get; set; }
        public int nIndex { get; set; }
        public string nForm { get; set; }
        public string nFormurl { get; set; }
        public string nAuthor { get; set; }
        public int uId { get; set; }
        public DateTime nAddTime { get; set; }
        public Nullable<int> nTalks { get; set; }
        public Nullable<int> nClicks { get; set; }
        public string nTitle { get; set; }
        public string nTitleSeo { get; set; }
        public string nTitlepic { get; set; }
        public string nTips { get; set; }
        public string nContent { get; set; }
        public string nTags { get; set; }
        public string nLinkurl { get; set; }
        public bool nIsPage { get; set; }
        public int nclass1 { get; set; }
        public Nullable<short> nClass2 { get; set; }
        public Nullable<short> nStatus { get; set; }
        public Nullable<byte> nLevel { get; set; }
        public Nullable<bool> nIsRecommand { get; set; }
        public Nullable<int> nGood { get; set; }
        public Nullable<int> nBad { get; set; }
        public Nullable<bool> nIsDel { get; set; }
        public int carId { get; set; }
    }
}
