//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class C_Person
    {
        public System.Guid pId { get; set; }
        public int pIndex { get; set; }
        public string pFirstChar { get; set; }
        public string pCnName { get; set; }
        public string pEnName { get; set; }
        public string pPenName { get; set; }
        public Nullable<bool> pSex { get; set; }
        public string pJob { get; set; }
        public string pNationality { get; set; }
        public string pNation { get; set; }
        public Nullable<System.DateTime> pBirthday { get; set; }
        /// <summary>
        /// 生肖
        /// </summary>
        public string pZodiac { get; set; }
        /// <summary>
        /// 星座
        /// </summary>
        public string pConstellation { get; set; }
        public Nullable<decimal> pHeight { get; set; }
        public Nullable<decimal> pWeight { get; set; }
        public string pBWH { get; set; }
        public string pUniversity { get; set; }
        public string pHomeProvince { get; set; }
        public string pHomeCity { get; set; }
        public string pHomeArea { get; set; }
        public string pNowProvice { get; set; }
        public string pNowCity { get; set; }
        public string pNowArea { get; set; }
        public string pNowPlace { get; set; }
        public string pBloodType { get; set; }
        public string pPhoto { get; set; }
        public string pSpeak { get; set; }
        public string pSinaBlog { get; set; }
        public string pTencentBlog { get; set; }
        public string pHomePage { get; set; }
        public string pTips { get; set; }
        public string pIntroduce { get; set; }
        public string pTags { get; set; }
        public System.Guid ClassId { get; set; }
        public Nullable<int> pFans { get; set; }
        public Nullable<int> pClicks { get; set; }
        public Nullable<System.DateTime> pAddTime { get; set; }
        public Nullable<int> pStatus { get; set; }
    }
}
