//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Photo
    {
        public System.Guid pId { get; set; }
        public string pUrl { get; set; }
        public string pDesc { get; set; }
        public Nullable<System.DateTime> pAddTime { get; set; }
        public Nullable<System.Guid> AlbumId { get; set; }
    }
}
