//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Question
    {
        public System.Guid qId { get; set; }
        public string qTitle { get; set; }
        public string qIntro { get; set; }
        public string qAsker { get; set; }
        public int qIndex { get; set; }
        public Nullable<System.Guid> personId { get; set; }
        public string qTags { get; set; }
        public Nullable<int> qGood { get; set; }
        public Nullable<int> qBad { get; set; }
        public Nullable<int> qClicks { get; set; }
        public Guid classId { get; set; }
        public Nullable<System.DateTime> qAddTime { get; set; }
    }
}
