//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User
    {
        public System.Guid uId { get; set; }
        public string uName { get; set; }
        public string uNickName { get; set; }
        public string uPwd { get; set; }
        public string uPhoto { get; set; }
        public Nullable<int> uAge { get; set; }
        public Nullable<bool> uSex { get; set; }
        public string uMobile { get; set; }
        public string uPhone { get; set; }
        public string uProvince { get; set; }
        public string uCity { get; set; }
        public string uZipCode { get; set; }
        public string uAddr { get; set; }
        public Nullable<System.DateTime> uBirth { get; set; }
        public string uRegIp { get; set; }
        public Nullable<System.DateTime> uLoginTime { get; set; }
        public string uLastIp { get; set; }
        public Nullable<short> uStatus { get; set; }
    }
}
